export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'


export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'


export const API_FAILURE = 'API_FAILURE'